### ISSUE TITLE
Potential bug in create-kpatch-module

### ISSUE THREAD

**Issue by desisnacks** [dynup/kpatch#813] opened 2018-03-28 19:31 UTC
**Potential bug in create-kpatch-module when running kpatch-build inside docker to build
against 4.4.27 kernel.**

I did use the following link to install necessary dependencies.
https://github.com/dynup/kpatch

Since we are building inside docker against an older kernel, my understanding is
Kpatch-build will try to build older format of live patch using  create-kpatch-module.
I do see both original .o and patched .o in the relevant directories inside docker.

But create-kpatch-module is not being called and I'm getting an error
indicating "Makefile target missing".

Upon further inspection (with -d oputput and from the script itself)
```
+ /usr/local/libexec/kpatch/create-kpatch-module /home/xyz/.kpatch/tmp/patch/tmp_output.o /home/xyz/.kpatch/tmp/patch/output.o
+ local to_stdout=1
+ [[ 1 -ge 2 ]]
+ [[ 1 -eq 1 ]]
+ tee -a /home/racker/.kpatch/build.log
+ check_pipe_status create-kpatch-module
+ rc=0
+ [[ 0 = 139 ]]
+ cd /home/xyz/.kpatch/tmp/patch
+ logger
+ KPATCH_BUILD=/source/linux
+ KPATCH_NAME=kpatch-4-4-0-2-modules-0-3-2-3-x86_64
+ KBUILD_EXTRA_SYMBOLS=/usr/lib/modules/4.4.0+2/extra/kpatch/Module.symvers
+ KPATCH_LDFLAGS=
+ make
```

This is where it's failing. The script comparison is with 139 which is SIGSEGV. I don't see
any core files either in the working directory.

I'm re-running the build again and will append any logs and more details.
- host kernel version
```
 uname -a
Darwin MVG0PGG8WL 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```
  - container OS : 

```uname -a
Linux 15e882430758 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
  - container gcc version

```[15e882430758] racker@docker > /usr/bin/gcc --versions
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

 - patch-build line

```
kpatch-build -d -n kpatch-4.4.0+2-modules-0.3.2-3.x86_64 -c ./kernel-x86_64.config -s . -v /usr/lib/debug/lib/modules/4.4.0+2/vmlinux meminfo-string2.patch --skip-cleanup
```

  - attach the input patch file

```[15e882430758] racker@docker > cat /source/linux/meminfo-string2.patch
diff --git i/fs/proc/meminfo.c w/fs/proc/meminfo.c
index 9155a5a0d3b9..45dba271f01c 100644
--- i/fs/proc/meminfo.c
+++ w/fs/proc/meminfo.c
@@ -131,7 +131,7 @@ static int meminfo_proc_show(struct seq_file *m, void *v)
 		"Committed_AS:   %8lu kB\n"
 		"VmallocTotal:   %8lu kB\n"
 		"VmallocUsed:    %8lu kB\n"
-		"VmallocChunk:   %8lu kB\n"
+		"VmallocChunk temp:   %8lu kB\n"
 #ifdef CONFIG_MEMORY_FAILURE
 		"HardwareCorrupted: %5lu kB\n"
 #endif
```

edit: @joe-lawrence, formatting cleanup

**Comment by desisnacks** [comment] 2018-03-28 21:13
[build.log](https://github.com/dynup/kpatch/files/1857795/build.log)

**Comment by joe-lawrence** [comment] 2018-03-28 21:32
Thanks for opening the bug report and providing the build.log file.
> This is where it's failing. The script comparison is with 139 which is SIGSEGV. I don't see
any core files either in the working directory.

Oh, after re-reading the script, I think what you see in the output is that the `${PIPESTATUS[0]}` *is* 0, and it's echoing the comparison against a SIGSEGV to the screen.  In this case, there's no issue, so there are no complaints about core files anywhere.

What does the output of `ls -al /home/xyz/.kpatch/tmp/patch` look like?  Is there a Makefile present in that directory?

**Comment by desisnacks** [comment] 2018-03-28 21:34
Thank you for the response.
Here is the info you requested.

ls -al /home/racker/.kpatch/tmp/patch
total 392
drwxr-xr-x 2 racker hypdev   4096 Mar 28 21:03 ./
drwxr-xr-x 6 racker hypdev   4096 Mar 28 21:03 ../
-rwxr-xr-x 1 racker hypdev 192776 Mar 28 21:03 output.o*
-rw-r--r-- 1 racker hypdev 193656 Mar 28 21:03 tmp_output.o

**Comment by joe-lawrence** [comment] 2018-03-28 21:45
Are you running kpatch-build from a git repo checkout, or did you install it to the system?

Also, do you have an instance of `DATADIR=/some/path/` in your build output (doesn't get saved into the build.log unfortunately).

**Comment by desisnacks** [comment] 2018-03-28 21:49
1. I cloned kpatch and did make install-kpatch-build inside the docker.
2. I have some Linux kern version also cloned  and point the kpatch-build command to use 
that Linux repo.
```
kpatch-build -d -n kpatch-4.4.0+2-modules-0.3.2-3.x86_64 -c ./kernel-x86_64.config -s . -v /usr/lib/debug/lib/modules/4.4.0+2/vmlinux meminfo-string2.patch --skip-cleanup
```
I don't see DATADIR but going to recheck again by capturing the output.

**Comment by joe-lawrence** [comment] 2018-03-28 21:54
> 1. I cloned kpatch and did make install-kpatch-build inside the docker.

Ooo, that's an interesting make target.  I think this only installed part of the tools.  (You can double check to see if `/usr/local/share/kpatch` exists, at least on a RHEL system.)

I would try doing a full install via `make install` .  That should create a template patch directory (example above) that gets copied into `/home/xyz/.kpatch/tmp/patch` as part of the kpatch-build.  Do that full install and re-try the build.

**Comment by desisnacks** [comment] 2018-03-28 21:58
Thank you again:So that has a different issue.
kernel-devel-4.9.87-linuxkit-aufs - is docker related.
E.g
```
[15e882430758] racker@docker > uname -r
4.9.87-linuxkit-aufs
[15e882430758] racker@docker > sudo make
make -C kpatch-build
make[1]: Entering directory `/source/kpatch/kpatch-build'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/source/kpatch/kpatch-build'
make -C kpatch
make[1]: Entering directory `/source/kpatch/kpatch'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/source/kpatch/kpatch'
make -C kmod
make[1]: Entering directory `/source/kpatch/kmod'
make -C core clean
make[2]: Entering directory `/source/kpatch/kmod/core'
Makefile:7: *** /lib/modules/4.9.87-linuxkit-aufs/build doesn\'t exist.  Try installing the kernel-devel-4.9.87-linuxkit-aufs RPM or linux-headers-4.9.87-linuxkit-aufs DEB..  Stop.
make[2]: Leaving directory `/source/kpatch/kmod/core'
make[1]: *** [clean] Error 2
make[1]: Leaving directory `/source/kpatch/kmod'
make: *** [build-kmod] Error 2
```

**Comment by cardoe** [comment] 2018-03-28 22:19
So ultimately the issue is can `kpatch-build` be used to build a patch file against the non-running kernel? I would expect that it could since this is often how kernel modules are built.

**Comment by joe-lawrence** [comment] 2018-03-28 23:36
> What @desisnacks is looking for is how to do make KVER=4.4.0+2 when uname -r is returning "4.9.87-linuxkit-aufs".

Yup, it's definitely possible.  First you'll need to rebuild kpatch itself (specifically the kpatch core module) against the desired kernel, overriding `KPATCH_BUILD` path.  For example, I'll run all of this from a git checkout of the repo:
```
% uname -r
4.4.0+
% make -s clean
% make KPATCH_BUILD=/lib/modules/3.10.0-693.el7.x86_64/build
...
make[2]: Entering directory `/root/kpatch.joe/kmod/core'
make -C /lib/modules/3.10.0-693.el7.x86_64/build M=/root/kpatch.joe/kmod/core kpatch.ko
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.el7.x86_64'
...
% modinfo ./kmod/core/kpatch.ko | grep vermagic
vermagic:       3.10.0-693.el7.x86_64 SMP mod_unload modversions 
```

Then run kpatch-build and provide it with `-s` and `-v` options that point to your target kernel source directory and vmlinux path:
```
./kpatch-build/kpatch-build \
    -s /root/rpmbuild/BUILD/kernel-3.10.0-693.el7/linux-3.10.0-693.el7.centos.x86_64 \
    -v /lib/debug/usr/lib/modules/3.10.0-693.el7.x86_64/vmlinux
    -t vmlinux \
    ./test/integration/centos-7/cmdline-string.patch
...
% modinfo kpatch-cmdline-string.ko | grep vermagic
vermagic:       3.10.0 SMP mod_unload modversions 

... reboot onto 3.10.0-693.el7.x86_64 ...

% uname -r
3.10.0-693.el7.x86_64
% ./kpatch/kpatch load kpatch-cmdline-string.ko 
loading core module: /root/kpatch.joe/kpatch/../kmod/core/kpatch.ko
loading patch module: kpatch-cmdline-string.ko
% cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-3.10.0-693.el7.x86_64 root=/dev/mapper/centos-root ro console=tty0 console=ttyS0,115200 rd_NO_PLYMOUTH crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=en_US.UTF-8 kpatch=1
```

In my example, these paths are all over the place since I'm hacking it together with a distro kernel... interestingly the vermagic didn't match exactly, but I think that's because I only did an `rpmbuild -bp` on my kernel source rpm.  Hopefully close enough to demonstrate the general idea.

**Comment by desisnacks** [comment] 2018-03-29 13:12
thanks @joe-lawrence. I will report you on this shortly. I did go past make/install for kpatch
instead of using install-kpatch-build as make target.

**Comment by desisnacks** [comment] 2018-03-29 15:59
```
+ cp -f /home/racker/.kpatch/tmp/patch/kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko /source/linux
+ [[ 1 -eq 0 ]]
+ echo SUCCESS
SUCCESS
```
Thanks @joe-lawrence , I am able to create lp. IF I may ask, can you share your specfile for building 
an rpm for this lp? I have similar setup and just trying to leverage. Thanks again! Immensely helpful.

**Comment by desisnacks** [comment] 2018-03-29 16:30
```
[root@69-183-22-655721 ~]# kpatch info kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko
Patch information for kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko:
filename:       /root/kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko
license:        GPL
depends:        kpatch
vermagic:       4.4.0+2+ SMP mod_unload modversions
parm:           replace:replace all previously loaded patch modules (bool)
[root@69-183-22-655721 ~]# uname -a
Linux 69-183-22-655721 4.4.0+2 #1 SMP Tue Mar 13 16:59:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@69-183-22-655721 ~]# kpatch load kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko
loading patch module: kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko
insmod: ERROR: could not insert module kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko: Unknown symbol in module
kpatch: failed to load module kpatch-4-4-0-2-modules-0-3-2-3-x86_64.ko
```
Further the load/install of the kpatch fails. I think this is because of an extra +
symbol in the modinfo (vermagic).

**Comment by joe-lawrence** [comment] 2018-03-29 18:11
> Further the load/install of the kpatch fails. I think this is because of an extra +
symbol in the modinfo (vermagic).

I believe the kernel build adds the additional '+' symbol if there are any outstanding git changes in the kernel source directory.  What does `git status` report from the kernel tree?

**Comment by joe-lawrence** [comment] 2018-03-29 19:56
That's strange as `klp_register_patch` should only be provided by a kernel configured with `CONFIG_LIVEPATCH`.  Can you double check that it's really set to off?  If so, I'll have to do some more digging on this.

**Comment by joe-lawrence** [comment] 2018-03-30 15:08
Reading back through the replies today, am I going crazy or did you report that the unknown symbol was `kpatch_root_kobj` ?  For some reason I went hunting that down, but now can't figure out why :-)

Does the kpatch module still fail to load after manually loading patch module?

**Comment by desisnacks** [comment] 2018-03-30 15:13
yes, unfortunately that still fails. 
```
[63026.551448] kpatch_4_4_0_2_modules_0_3_2_3_x86_64: disagrees about version of symbol kpatch_register
[63026.551458] kpatch_4_4_0_2_modules_0_3_2_3_x86_64: Unknown symbol kpatch_register (err -22)
[63026.551480] kpatch_4_4_0_2_modules_0_3_2_3_x86_64: disagrees about version of symbol kpatch_unregister
[63026.551484] kpatch_4_4_0_2_modules_0_3_2_3_x86_64: Unknown symbol kpatch_unregister (err -22)
[63026.551490] kpatch_4_4_0_2_modules_0_3_2_3_x86_64: no symbol version for kpatch_root_kobj
[63026.551493] kpatch_4_4_0_2_modules_0_3_2_3_x86_64: Unknown symbol kpatch_root_kobj (err -22)
[root@69-183-22-655721 ~]# lsmod | grep kpatch
kpatch                 53248  0
```

**Comment by joe-lawrence** [comment] 2018-03-30 20:58
That looks like a discrepancy in Modules.symvers.  Maybe try `rmmod kpatch && make clean && make KPATCH_BUILD=/your/kernel/path && make install` one more time to update the core kpatch.ko module.  Unfortunately I don't have a docker setup handy, so I won't be able to try until maybe next week.

**Comment by desisnacks** [comment] 2018-04-02 13:48
I have already tried that and still the same issue. While loading the .ko , fails to load.

**Comment by joe-lawrence** [comment] 2018-04-02 15:09
Alright, this is do-able, but remember that it is strongly recommended that the kpatch module be build using the same exact version of gcc as the target kernel.  Prepare your docker build container accordingly.  As an experiment, I did the following:

* Container Host: CentOS 7.4 running 3.10.0-693.el7.x86_64
* Container image: Centos 7.4
* Install kernel-devel, debuginfo, etc. for 3.10.0-693.21.1.el7.x86_6
* Build kpatch and sample kpatch module
* Upgrade the container host to 3.10.0-693.el7.x86_64 and reboot
* Load the kpatch on the container host

On the container host, run docker and map `/root` into the container so we can save the generated kpatch stuff to the host:
```
(host)
% cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
% uname -r
3.10.0-693.el7.x86_64

% docker run -i -t --rm -v /root:/root:Z centos /bin/bash
```

In the container, install all the necessary kpatch build requirements, including the kernel-devel, debuginfo for the *target* kpatch kernel (not shown here).  Then build kpatch and the kpatch module for that kernel:
```
(container)
% git clone https://github.com/dynup/kpatch
% cd kpatch
% KPATCH_KVER=3.10.0-693.21.1.el7
% make -s KPATCH_BUILD=/usr/src/kernels/${KPATCH_KVER}.x86_64
% modinfo ./kmod/core/kpatch.ko  | grep vermagic
vermagic:       3.10.0-693.21.1.el7.x86_64 SMP mod_unload modversions

./kpatch-build/kpatch-build \
    -s /root/rpmbuild/BUILD/kernel-${KPATCH_KVER}/linux-${KPATCH_KVER}.x86_64 \
    -v /lib/debug/usr/lib/modules/${KPATCH_KVER}.x86_64/vmlinux \
    -t vmlinux \
    --skip-cleanup \
    ./test/integration/centos-7/cmdline-string.patch

... snip ...
SUCCESS
% modinfo ./kpatch-cmdline-string.ko | grep vermagic
vermagic:       3.10.0 SMP mod_unload modversions
```
(I don't have the time right now to figure out how to adjust the source rpm's include files to specify the right vermagic string that a full rpmbuild generates.)

Shut the container down.

Back on the docker host, upgrade the kernel and reboot:
```
(host)
% yum upgrade -y kernel
...
% reboot
...
% uname -r
3.10.0-693.21.1.el7.x86_6
```

The kpatch core module and patch module that the container built for our new kernel now successfully loads:
```
(host)
% cd kpatch
% ./kpatch/kpatch load ./kpatch-cmdline-string.ko                                                                                                 
loading core module: /root/kpatch/kpatch/../kmod/core/kpatch.ko
loading patch module: ./kpatch-cmdline-string.ko

% lsmod | grep kpatch
kpatch_cmdline_string    14039  1 
kpatch                 51787  1 kpatch_cmdline_string

% cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-3.10.0-693.21.1.el7.x86_64 root=/dev/mapper/centos-root ro console=tty0 console=ttyS0,115200 rd_NO_PLYMOUTH crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=en_US.UTF-8 kpatch=1
```

How different are the steps that you are trying?

**Comment by jpoimboe** [comment] 2018-04-02 18:53
I agree that it sounds like a Module.symvers mismatch.

We always build kpatch.ko out-of-tree, does your kernel instead have it in-tree?

Also. after running with `-d`, check `~/.kpatch/tmp/patch/Module.symvers`.  It should be blank.

**Comment by desisnacks** [comment] 2018-04-03 13:36
kpatch.ko is built out of tree. The sequence of steps of approximately similar except my host
OS is Mac OS X and not native Linux. There are 3 variables instead of 2 as in your case.
OS X version: Darwin MVG0PGG8WL 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Docker Linux version: 4.9.87-linuxkit-aufs
Kpatch target kernel version: 4.4.27
Compiler version during the build and on the target kernel is the same.

**Comment by desisnacks** [comment] 2018-04-13 13:44
It appears that the kernel version of 4.4.0+2 is the one that may be causing the problem.
Basically this kernel's actual version is 4.4.27 but Citrix is shipping Xen with version being
clobbered. Thanks for your inputs/help.

**Comment by jpoimboe** [comment] 2018-04-13 13:56
Thanks, I will close the issue for now.

**Closed by jpoimboe** 2018-04-13 13:56 UTC
