### ISSUE TITLE
hard lockup with kpatch / while installing kpatch

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#774] opened 2017-12-05 09:10 UTC
Today a bunch of 50 - 80 servers crashed while trying to apply / load kpatch.

All of them show nearly the same stack trace:
```
2017-12-05 07:00:37 kpatch: loading out-of-tree module taints kernel.
2017-12-05 07:00:50 NMI watchdog: Watchdog detected hard LOCKUP on cpu 0
2017-12-05 07:00:50 Modules linked in: kpatch_4_4_83_529_ph_1512286016(O+) kpatch(O) cpuid netconsole xt_multiport ipt_REJECT nf_reject_ipv4 xt_set iptable_filter ip_tables x_tables ip_set_hash_net ip_set nfnetlink bonding tcp_htcp sch_fq_codel ipmi_devintf ast ttm sb_edac drm_kms_helper edac_core drm fb_sys_fops x86_pkg_temp_thermal syscopyarea sysfillrect sysimgblt kvm_intel kvm irqbypass ipmi_si crc32_pclmul wmi i2c_i801 shpchp ipmi_msghandler ghash_clmulni_intel button coretemp 8021q garp fuse btrfs dm_mod raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq raid1 raid0 multipath linear usb_storage ohci_hcd usbhid md_mod xhci_pci sg sd_mod ehci_pci igb xhci_hcd i2c_algo_bit ehci_hcd i40e ahci i2c_core mpt3sas raid_class ptp usbcore libahci usb_common pps_core scsi_transport_sas
2017-12-05 07:00:50 CPU: 0 PID: 11 Comm: migration/0 Tainted: G O 4.4.83+529-ph 0000001
2017-12-05 07:00:50 Hardware name: Supermicro Super Server/X10SRH-CF, BIOS 1.0b 05/18/2015
2017-12-05 07:00:50 task: ffff8801894ea580 ti: ffff8801894f4000 task.ti: ffff8801894f4000
2017-12-05 07:00:50 RIP: 0010:[<ffffffff8a107142>] [<ffffffff8a107142>] fde_pointer_type+0x32/0x110
2017-12-05 07:00:50 RSP: 0018:ffff8801894f78f0 EFLAGS: 00000002
2017-12-05 07:00:50 RAX: 000000000000007a RBX: ffffffff8ab171f1 RCX: 000000000008a310
2017-12-05 07:00:50 RDX: 0000000000000014 RSI: ffffffff8b232ba0 RDI: ffffffff8ab171e8
2017-12-05 07:00:50 RBP: ffff8801894f7910 R08: 0000000000000001 R09: 0000000000000007
2017-12-05 07:00:50 R10: 0000000000000001 R11: 0000000000000040 R12: 00000000000f12e0
2017-12-05 07:00:50 R13: ffffffff8aba14f8 R14: ffffffff8ab171e8 R15: 000000000000000b
2017-12-05 07:00:50 FS: 0000000000000000(0000) GS:ffff880c7fc00000(0000) knlGS:0000000000000000
2017-12-05 07:00:50 CS: 0010 DS: 0000 ES: 0000 CR0: 0000000080050033
2017-12-05 07:00:50 CR2: 00007fd5f2e1a008 CR3: 00000006fa72f000 CR4: 00000000001406f0Stack:
2017-12-05 07:00:50 ffffffff8ab171f1 fffffffffffffffc 00000000000f12e0 ffffffff8aba14f8
2017-12-05 07:00:50 ffff8801894f7b38 ffffffff8a107fa9 0000000000000010 ffffffff8b232ba0
2017-12-05 07:00:50 ffff8801894f7b80 ffffffff8a25421b ffffffff8a6db5ed ffffffff8a2541d0
2017-12-05 07:00:50 Call Trace:
2017-12-05 07:00:50 [<ffffffff8a107fa9>] unwind+0x239/0x1100
2017-12-05 07:00:50 [<ffffffff8a0099d7>] dump_trace_unwind+0x67/0xe0
2017-12-05 07:00:50 [<ffffffff8a009b17>] try_stack_unwind+0xa7/0x190
2017-12-05 07:00:50 [<ffffffff8a008dc4>] dump_trace+0x64/0x380
2017-12-05 07:00:50 [<ffffffff8a0159f2>] save_stack_trace_tsk+0x22/0x40
2017-12-05 07:00:50 [<ffffffffc08f30d0>] kpatch_verify_activeness_safety+0x70/0x2c0 [kpatch]
2017-12-05 07:00:50 [<ffffffffc08f46aa>] kpatch_apply_patch+0x1a/0x200 [kpatch]
2017-12-05 07:00:50 [<ffffffff8a11d7e2>] multi_cpu_stop+0xc2/0xf0
2017-12-05 07:00:50 [<ffffffff8a11d9d0>] cpu_stopper_thread+0xb0/0x150
2017-12-05 07:00:50 [<ffffffff8a0a6d69>] smpboot_thread_fn+0x139/0x1a0
2017-12-05 07:00:50 [<ffffffff8a0a389b>] kthread+0xeb/0x110
2017-12-05 07:00:50 [<ffffffff8a6db94f>] ret_from_fork+0x3f/0x70
2017-12-05 07:00:50 DWARF2 unwinder stuck at ret_from_fork+0x3f/0x70
2017-12-05 07:00:50 Leftover inexact backtrace: [1090783.680424]
2017-12-05 07:00:50 [<ffffffff8a0a37b0>] ? kthread_park+0x60/0x60
2017-12-05 07:00:50 Code: 08 01 0f 85 fb 00 00 00 55 48 89 e5 41 55 41 54 53 48 8d 5f 09 48 83 ec 08 0f b6 47 09 48 89 5d e0 84 c0 0f 84 8f 00 00 00 8b 17 <3c> 7a 4c 8d 6c 17 04 75 74 4c 89 ea 31 f6 48 89 df 48 29 da e8
2017-12-05 07:00:50 Kernel panic - not syncing: Hard LOCKUP
2017-12-05 07:00:50 CPU: 0 PID: 11 Comm: migration/0 Tainted: G O 4.4.83+529-ph 0000001
2017-12-05 07:00:50 Hardware name: Supermicro Super Server/X10SRH-CF, BIOS 1.0b 05/18/2015
2017-12-05 07:00:50 0000000000000000 ffff880c7fc05b50 ffffffff8a3cdb83 ffffffff8aa0ca8b
2017-12-05 07:00:50 ffff880c7fc05be0 ffff880c7fc05bd0 ffffffff8a156ff8 0000000000000008
2017-12-05 07:00:50 ffff880c7fc05be0 ffff880c7fc05b78 ffffc90006db4800 0000000000000086
2017-12-05 07:00:50 Call Trace:
2017-12-05 07:00:50 [<ffffffff8a009be5>] try_stack_unwind+0x175/0x190
2017-12-05 07:00:50 [<ffffffff8a008dc4>] dump_trace+0x64/0x380
2017-12-05 07:00:50 [<ffffffff8a009c4d>] show_trace_log_lvl+0x4d/0x60
2017-12-05 07:00:50 [<ffffffff8a0091e8>] show_stack_log_lvl+0x108/0x170
2017-12-05 07:00:50 [<ffffffff8a009ca5>] show_stack+0x25/0x70
2017-12-05 07:00:50 [<ffffffff8a3cdb83>] dump_stack+0x63/0x90
2017-12-05 07:00:50 [<ffffffff8a156ff8>] panic+0xd0/0x21e
2017-12-05 07:00:50 [<ffffffff8a11ec1d>] watchdog_overflow_callback+0xed/0xf0
2017-12-05 07:00:50 [<ffffffff8a1529e8>] __perf_event_overflow+0x88/0x1d0
2017-12-05 07:00:50 [<ffffffff8a153534>] perf_event_overflow+0x14/0x20
2017-12-05 07:00:50 [<ffffffff8a023efe>] intel_pmu_handle_irq+0x1ce/0x470
2017-12-05 07:00:50 [<ffffffff8a01b248>] perf_event_nmi_handler+0x28/0x50
2017-12-05 07:00:50 [<ffffffff8a00a436>] nmi_handle+0x66/0x120
2017-12-05 07:00:50 [<ffffffff8a00a61a>] do_nmi+0x12a/0x400
2017-12-05 07:00:50 [<ffffffff8a6dd9f1>] end_repeat_nmi+0x1a/0x1e
2017-12-05 07:00:50 DWARF2 unwinder stuck at end_repeat_nmi+0x1a/0x1e
2017-12-05 07:00:50 Leftover inexact backtrace: [1090783.705971]
2017-12-05 07:00:50 <NMI> [<ffffffff8a107142>] ? fde_pointer_type+0x32/0x110
2017-12-05 07:00:50 [<ffffffff8a107142>] ? fde_pointer_type+0x32/0x110
2017-12-05 07:00:50 [<ffffffff8a107142>] ? fde_pointer_type+0x32/0x110
2017-12-05 07:00:50 <<EOE>> [<ffffffff8a107fa9>] unwind+0x239/0x1100
2017-12-05 07:00:50 [<ffffffff8a25421b>] ? find_dcookie+0x4b/0x50
2017-12-05 07:00:50 [<ffffffff8a6db5ed>] ? entry_SYSCALL_64_fastpath+0x11/0x71
2017-12-05 07:00:50 [<ffffffff8a2541d0>] ? devpts_pty_kill+0xa0/0xa0
2017-12-05 07:00:50 [<ffffffff8a0a37b0>] ? kthread_park+0x60/0x60
2017-12-05 07:00:50 [<ffffffff8a0fdb80>] ? do_futex+0x500/0x500
2017-12-05 07:00:50 [<ffffffff8a0b3e32>] ? in_sched_functions+0x12/0x40
2017-12-05 07:00:50 [<ffffffff8a0099d7>] dump_trace_unwind+0x67/0xe0
2017-12-05 07:00:50 [<ffffffff8a009b17>] try_stack_unwind+0xa7/0x190
2017-12-05 07:00:50 [<ffffffff8a6db5ee>] ? entry_SYSCALL_64_fastpath+0x12/0x71
2017-12-05 07:00:50 [<ffffffff8a008dc4>] dump_trace+0x64/0x380
2017-12-05 07:00:50 [<ffffffff8a0ae9ff>] ? ttwu_do_activate+0x6f/0x80
2017-12-05 07:00:50 [<ffffffff8a0159f2>] save_stack_trace_tsk+0x22/0x40
2017-12-05 07:00:50 [<ffffffffc08f30d0>] kpatch_verify_activeness_safety+0x70/0x2c0 [kpatch]
2017-12-05 07:00:50 [<ffffffffc08f46aa>] kpatch_apply_patch+0x1a/0x200 [kpatch]
2017-12-05 07:00:50 [<ffffffff8a11d7e2>] multi_cpu_stop+0xc2/0xf0
2017-12-05 07:00:50 [<ffffffff8a11d720>] ? cpu_stop_queue_work+0x80/0x80
2017-12-05 07:00:50 [<ffffffff8a11d9d0>] cpu_stopper_thread+0xb0/0x150
2017-12-05 07:00:50 [<ffffffff8a0abe38>] ? finish_task_switch+0x1b8/0x280
2017-12-05 07:00:50 [<ffffffff8a6d6a4d>] ? thread_return+0x38/0x54b
2017-12-05 07:00:50 [<ffffffff8a0a6d69>] smpboot_thread_fn+0x139/0x1a0
2017-12-05 07:00:50 [<ffffffff8a0a6c30>] ? sort_range+0x30/0x30
2017-12-05 07:00:50 [<ffffffff8a0a389b>] kthread+0xeb/0x110
2017-12-05 07:00:50 [<ffffffff8a0a37b0>] ? kthread_park+0x60/0x60
2017-12-05 07:00:50 [<ffffffff8a6db94f>] ret_from_fork+0x3f/0x70
2017-12-05 07:00:50 [<ffffffff8a0a37b0>] ? kthread_park+0x60/0x60
2017-12-05 07:00:51 Shutting down cpus with NMI
2017-12-05 07:00:51 Kernel Offset: 0x9000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

**Comment by jpoimboe** [comment] 2017-12-05 14:01
I assume this is a SUSE kernel?  Looks like the lockup is in the DWARF unwinder.

**Comment by disaster123** [comment] 2017-12-05 14:12
Yes it is but the unwinder is only running / started when a trace is happening? Isn‘t it?

**Comment by jpoimboe** [comment] 2017-12-05 14:21
Yes, but maybe I'm missing your point.  Is it not a bug in the SUSE DWARF unwinder?

**Comment by disaster123** [comment] 2017-12-06 08:36
Might be but why is Kpatch in the stack trace? Does this not mean Kpatch triggered hard lockup in dwarf? My assumption was that dwarf is only running when a stack trace gets generated.

**Comment by jpoimboe** [comment] 2017-12-06 13:51
kpatch calls the kernel unwinder to save the stack of every task, as part of its safety check, before patching the system.  kpatch is shown in the stack dump because it's in the call path: when it called the unwinder, the unwinder hung, presumably due to a deadlock of some kind.

**Comment by disaster123** [comment] 2017-12-06 14:24
Ah thanks!! That makes sense.

**Comment by disaster123** [comment] 2017-12-06 20:50
Even though it might be a suse dwarf issue - it only happens on systems running / using ceph (in userspace). If i stop any process using ceph as client or server applying work fine.

**Comment by jpoimboe** [comment] 2018-03-22 18:56
Closing, since this seems to be an issue with the openSUSE DWARF unwinder.

**Closed by jpoimboe** 2018-03-22 18:56 UTC
