### ISSUE TITLE
dirtycow & 4.4.21 (ubuntu 4.4.0-42-62) error building

### ISSUE THREAD

**Issue by SvenDowideit** [dynup/kpatch#633] opened 2016-12-11 04:47 UTC
I've been playing around with this for a day or so, but don't know enough to figure out what's up.

(using kpatch master at a963ee7 today, if that matters)

I've tried the normal dirtycow patch, and I've tried moving the define into gup.c, and also unrolling the new static function inline.

I'm consistently getting:

```
Using source directory at /usr/src/09a763a
Testing patch file
checking file mm/gup.c
Reading special section data
Building original kernel
Building patched kernel
Extracting new and modified ELF sections
gup.o: changed function: follow_page_pte
gup.o: changed function: __get_user_pages
/usr/local/libexec/kpatch/create-diff-object: ERROR: gup.o: kpatch_create_dynamic_rela_sections: \
1973: lookup_local_symbol pmd_val (gup.c) needed for .text.follow_page_pte
```

I presumed this was something on my end, but after being shown https://github.com/dynup/kpatch/issues/614, I wonder if its more complicated.

**Comment by jpoimboe** [comment] 2016-12-11 17:09
I wonder if there's a mismatch between the binaries kpatch-build is building and the vmlinux which was provided to it.  It looks like the gup.o binaries built by kpatch-build have a local pmd_val symbol, whereas the vmlinux file does not.  Is kpatch-build using the same compiler toolchain and the same kernel config that were used to build the vmlinux file?

If that doesn't clear things up, the following details might help:

1) the full kpatch-build command line arguments
2) run again with -d (ignoring the output) and provide the ~/.kpatch/tmp/orig/mm/gup.o and  ~/.kpatch/tmp/patched/mm/gup.o files somewhere (or email them to me)
3) give the output of nm vmlinux | grep pmd_val

**Comment by SvenDowideit** [comment] 2016-12-12 10:42
the builds should be identical, as all 3 builds are being done in the same container - but I've been having trust issues all week :)

I'm running `kpatch-build --sourcedir /usr/src/31c1f86-dirty/ dirtycow.patch --vmlinux /usr/src/31c1f86-dirty/vmlinux` - pretty much just after building the kernel with DEBUG_INFO

I'll gather the rest when I get back to civilization, it seems the 4g network here at the beach got congested right about the time when most of the schools finished (gee, what a surprise)

**Comment by SvenDowideit** [comment] 2016-12-13 23:02
(the original non-kpatch build vmlinuz)
```
root@5b01d4415139:/usr/src/b5a4c2d# nm vmlinux | grep pmd_val
ffffffff810183f7 t pmd_val
ffffffff81050bcf t pmd_val
ffffffff81051a63 t pmd_val
ffffffff81053870 t pmd_val
ffffffff81056e71 t pmd_val
ffffffff810575c3 t pmd_val
ffffffff81158f0f t pmd_val
ffffffff8115a273 t pmd_val
ffffffff8115f033 t pmd_val
ffffffff81163c18 t pmd_val
ffffffff811647c0 t pmd_val
ffffffff8116579e t pmd_val
ffffffff81169e36 t pmd_val
ffffffff8116afdf t pmd_val
ffffffff8116c5ee t pmd_val
ffffffff81176920 t pmd_val
ffffffff8117a211 t pmd_val
ffffffff81183730 t pmd_val
ffffffff81186172 t pmd_val
ffffffff8118a627 t pmd_val
ffffffff81195cf9 t pmd_val
ffffffff811d307d t pmd_val
ffffffff811ec59d t pmd_val
ffffffff815ac3e2 t pmd_val
ffffffff81018341 T __raw_callee_save_xen_pmd_val
ffffffff8101a6ff T xen_pmd_val
```

**Comment by jpoimboe** [comment] 2016-12-14 02:13
Hm, my original theory about a compile mismatch was probably wrong.  I'm guessing all those pmd_val()'s are places where gcc decided to un-inline pmd_val() from arch/x86/include/asm/paravirt.h, due to CONFIG_OPTIMIZE_INLINING.  But that shouldn't be a problem.  Can you provide your kernel config and the gcc version?  Going to see if I can recreate.

**Comment by SvenDowideit** [comment] 2016-12-14 03:58
darn :)

`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)`


[config.txt](https://github.com/dynup/kpatch/files/650766/config.txt)

I'm actually building this for RancherOS, and from the next release, we're hoping to be using mainline 4.9, but its a useful learning place for us.

**Comment by jpoimboe** [comment] 2016-12-14 17:03
Nice, I had no idea github supported attachments.  Will see if I can recreate.

**Comment by jpoimboe** [comment] 2016-12-14 20:49
I was able to recreate it.  This is actually a duplicate of #604.  In retrospect we should have had a better error message for this.  Will follow up on that issue.

**Closed by jpoimboe** 2016-12-14 20:49 UTC
