### ISSUE TITLE
About the DATADIR variable in kpatch-build script

### ISSUE THREAD

**Issue by NonerKao** [dynup/kpatch#597] opened 2016-06-24 15:53 UTC
Hi,

If I understand correctly, the subroutine find_dir has to assign a right value to DATADIR, which should be the kmod directory in the source tree.  However, the command make install only installs the kmod/patch part.  This seems to be insufficient because, in the subroutine find_core_symver, the script needs the access of kmod/core/Module.symvers.

Actually, I am packaging this project for Arch Linux on AUR, which currently works fine with some additional installation command.

**Comment by jpoimboe** [comment] 2016-06-28 06:19
I haven't looked into this problem much, but it seems to be working fine for me.  After a make install, I have:
```
/usr/local/lib/kpatch/4.5.7-300.fc24.x86_64/Module.symvers
```

**Comment by flaming-toast** [comment] 2016-06-28 22:22
@NonerKao Do you happen to have `BUILDMOD` manually set in your environment? By default it is set to "yes", and `kmod/core/Module.symvers` will be properly installed with `make install`. If it's set to "no"  none of the kmod/core stuff will be installed. 

After running `make -d BUILDMOD=yes install` (-d for debug) from the repo root directory I see:
```
/usr/bin/install -m 644 core/kpatch.ko /usr/local/lib/kpatch/4.2.3-200.fc22.x86_64+debug
/usr/bin/install -m 644 core/Module.symvers /usr/local/lib/kpatch/4.2.3-200.fc22.x86_64+debug
/usr/bin/install -d /usr/local/share/kpatch/patch
(etc...)
```

**Comment by NonerKao** [comment] 2016-06-29 03:36
Thanks for both of your comments.  I was looking at `/usr/local/share` only and didn't notice that Module.symvers was installed to somewhere under `/usr/local/lib`.  Sorry, that was my bad.
This issue can be closed.

**Comment by flaming-toast** [comment] 2016-06-29 03:44
@NonerKao No problem, glad the issue is resolved :-)

**Closed by flaming-toast** 2016-06-29 03:44 UTC
