### ISSUE TITLE
testing: create-diff-object segfaults when building replace-section-references.patch on Fedora 25

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#629] opened 2016-12-05 16:44 UTC
As seen when running #624 :

**OS:** Fedora 25

**kernel version**: 4.8.6-300.fc25.x86_64
**gcc version**: gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)

```
Core was generated by `/usr/local/libexec/kpatch/create-diff-object orig/arch/x86/kvm/x86.o patched/ar'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000407fd7 in kpatch_rebuild_rela_section_data (sec=0xa980f0) at create-diff-object.c:2280
2280                            relas[index].r_info = GELF_R_INFO(rela->sym->index, rela->type);
Missing separate debuginfos, use: dnf debuginfo-install elfutils-libelf-0.167-2.fc25.x86_64 glibc-2.24-3.fc25.x86_64 zlib-1.2.8-10.fc24.x86_64
(gdb) p index
$1 = 0
(gdb) p *rela
$2 = {list = {next = 0xa98280, prev = 0xa98178}, rela = {r_offset = 0, r_info = 0, r_addend = 0}, sym = 0x0, type = 1, addend = 4, offset = 0, string = 0x0}
                                                                                                  ^^^^^^^^^
```

**Comment by joe-lawrence** [comment] 2016-12-07 15:17
A little bit more information from another generated core file:
```
  (gdb) p rela
  $1 = (struct rela *) 0x12f8240
  (gdb) p *rela
  $2 = {list = {next = 0x12f8290, prev = 0x12f8188}, rela = {r_offset = 0,
        r_info = 0, r_addend = 0}, sym = 0x0, type = 1, addend = 4,
        offset = 0, string = 0x0}

  (gdb) p sec
  $3 = (struct section *) 0x12f8100
  (gdb) p *sec
  $4 = {list = {next = 0x12f8c40, prev = 0x12f7e80}, twin = 0x0,
        sh = {sh_name = 0, sh_type = 4, sh_flags = 0, sh_addr = 0,
        sh_offset = 0, sh_size = 432, sh_link = 22, sh_info = 27,
        sh_addralign = 8, sh_entsize = 24}, data = 0x12f7ff0,
        name = 0x12f7db0 ".rela.kpatch.dynrelas", index = 28, status = NEW,
        include = 0, ignore = 0, grouped = 0, {{base = 0x12f7e80,
        relas = {next = 0x12f8240, prev = 0x12f8b00}}, {rela = 0x12f7e80,
        secsym = 0x12f8240, sym = 0x12f8b00}}}
```
Possibly a red herring, these look bogus (according to comments, d_type is supposed to be ELF_T_RELA.):
```
  (gdb) p *sec->data
  $5 = {d_buf = 0x188ae10, d_type = 3902196632, d_version = 32606, d_size = 432, d_off = 0, d_align = 0}
                                    ^^^^^^^^^^              ^^^^^
```
Adding debug to kpatch_create_dynamic_rela_sections() for section with name
".rela.kpatch.dynrelas", I see the following:
```
  sec(0x12f8100) .rela.kpatch.dynrelas
  sec(0x12f8100) .rela.kpatch.dynrelas !strcmp
> rela(0x12f8240) sym((nil))=NULL                      type=1, offset=0
  rela(0x12f8290) sym(0x12f7700)=.kpatch.strings       type=1, offset=32
  rela(0x12f8380) sym(0x12f7700)=.kpatch.strings       type=1, offset=40
  rela(0x18b14f0) sym(0x188b3c0)=kvm_define_shared_msr type=1, offset=56
  rela(0x12f83d0) sym(0x12f7700)=.kpatch.strings       type=1, offset=88
  rela(0x12f84c0) sym(0x12f7700)=.kpatch.strings       type=1, offset=96
  rela(0x18b6630) sym(0x188b3c0)=kvm_define_shared_msr type=1, offset=112
  rela(0x12f8510) sym(0x12f7700)=.kpatch.strings       type=1, offset=144
  rela(0x12f8620) sym(0x12f7700)=.kpatch.strings       type=1, offset=152
  rela(0x18b6680) sym(0x188b3c0)=kvm_define_shared_msr type=1, offset=168
  rela(0x12f8740) sym(0x12f7700)=.kpatch.strings       type=1, offset=200
  rela(0x12f8790) sym(0x12f7700)=.kpatch.strings       type=1, offset=208
  rela(0x18b66d0) sym(0x188b3c0)=kvm_define_shared_msr type=1, offset=224
  rela(0x12f8880) sym(0x12f7700)=.kpatch.strings       type=1, offset=256
  rela(0x12f88d0) sym(0x12f7700)=.kpatch.strings       type=1, offset=264
  rela(0x18b6720) sym(0x188b3c0)=kvm_define_shared_msr type=1, offset=280
  rela(0x12f89c0) sym(0x12f7700)=.kpatch.strings       type=1, offset=312
  rela(0x12f8b00) sym(0x12f7700)=.kpatch.strings       type=1, offset=320
```
but kpatch_create_dynamic_rela_sections() does no further processing of this
section, as it hits this string comparision:
```
		if (!strcmp(sec->name, ".rela.kpatch.funcs") ||
		    !strcmp(sec->name, ".rela.kpatch.dynrelas"))
			continue;
```

Continuing the instrumentation (going back in program execution time),
kpatch_create_dynamic_rela_sections() allocated a dynrela with the same
pointer value, assigning an empty sym value here:
```
  dynrela(0x12f8240) type=1 addend=4 offset=0x0 sym((nil))=NULL sec->base->name(0x7f5ee80c7bc8) __bug_table

			/* add rela to fill in dest field */
			ALLOC_LINK(dynrela, &relasec->relas);
			if (sec->base->sym)
				dynrela->sym = sec->base->sym;
			else
>				dynrela->sym = sec->base->secsym;
			dynrela->type = R_X86_64_64;
			dynrela->addend = rela->offset;
			dynrela->offset = index * sizeof(*dynrelas);
```
Which indicates that both sec->base->sym *and* sec->base->secsym are both
NULL.

**Comment by jpoimboe** [comment] 2016-12-19 23:13
As it turns out, this is a duplicate of #628, and it will be fixed by PR #643.

**Closed by jpoimboe** 2016-12-19 23:13 UTC

**Comment by jpoimboe** [comment] 2016-12-19 23:31
Create PR #644 to print an error message instead of seg faulting for this condition.

**Comment by joe-lawrence** [comment] 2016-12-20 15:58
:+1:

@jpoimboe : for PR #624 should we rename ```fedora-25/replace-section-references.patch``` with a "-FAIL" so ```kpatch-test``` knows the expected outcome?
