### ISSUE TITLE
Jump label issues are triggered from an unrelated function

### ISSUE THREAD

**Issue by tli16** [dynup/kpatch#1124] opened 2020-07-10 20:04 UTC
Hi, 
We noticed some bugs when we were trying to patch function `md_update_sb` in drivers/md/md.c. The following two patch files are almost exactly same, except the second one has one more blank line deletion at line 36. 
patch file1: 
```
diff --git a/drivers/md/md.c b/drivers/md/md.c
index 5599712d478e..2352d1cadb4f 100644
--- a/drivers/md/md.c
+++ b/drivers/md/md.c
@@ -2546,8 +2546,8 @@ void md_update_sb(struct mddev *mddev, int force_change)
    sync_sbs(mddev, nospares);
    spin_unlock(&mddev->lock);

-   pr_debug("md: updating %s RAID superblock on device (in sync %d)\n",
-        mdname(mddev), mddev->in_sync);
+   /* pr_debug("md: updating %s RAID superblock on device (in sync %d)\n", */
+   /*   mdname(mddev), mddev->in_sync); */

    if (mddev->queue)
        blk_add_trace_msg(mddev->queue, "md md_update_sb");
@@ -2563,9 +2563,9 @@ void md_update_sb(struct mddev *mddev, int force_change)
            md_super_write(mddev,rdev,
                       rdev->sb_start, rdev->sb_size,
                       rdev->sb_page);
-           pr_debug("md: (write) %s's sb offset: %llu\n",
-                bdevname(rdev->bdev, b),
-                (unsigned long long)rdev->sb_start);
+           /* pr_debug("md: (write) %s's sb offset: %llu\n", */
+           /*   bdevname(rdev->bdev, b), */
+           /*   (unsigned long long)rdev->sb_start); */
            rdev->sb_events = mddev->events;
            if (rdev->badblocks.size) {
                md_super_write(mddev, rdev,
@@ -2575,9 +2575,10 @@ void md_update_sb(struct mddev *mddev, int force_change)
                rdev->badblocks.size = 0;
            }

-       } else
-           pr_debug("md: %s (skipping faulty)\n",
-                bdevname(rdev->bdev, b));
+       } else {
+           /* pr_debug("md: %s (skipping faulty)\n", */
+           /*   bdevname(rdev->bdev, b));*/
+       }

        if (mddev->level == LEVEL_MULTIPATH)
            /* only need to write one superblock... */
@@ -2596,8 +2597,8 @@ void md_update_sb(struct mddev *mddev, int force_change)
        /* have to write it out again */
        goto repeat;
    wake_up(&mddev->sb_wait);
-   if (test_bit(MD_RECOVERY_RUNNING, &mddev->recovery))
-       sysfs_notify(&mddev->kobj, NULL, "sync_completed");
+   /*if (test_bit(MD_RECOVERY_RUNNING, &mddev->recovery)) */
+   /*  sysfs_notify(&mddev->kobj, NULL, "sync_completed"); */

    rdev_for_each(rdev, mddev) {
        if (test_and_clear_bit(FaultRecorded, &rdev->flags))
```
patch file 2:
```
diff --git a/drivers/md/md.c b/drivers/md/md.c
index 5599712d478e..9cb1cf172a66 100644
--- a/drivers/md/md.c
+++ b/drivers/md/md.c
@@ -2546,8 +2546,8 @@ void md_update_sb(struct mddev *mddev, int force_change)
    sync_sbs(mddev, nospares);
    spin_unlock(&mddev->lock);

-   pr_debug("md: updating %s RAID superblock on device (in sync %d)\n",
-        mdname(mddev), mddev->in_sync);
+   /* pr_debug("md: updating %s RAID superblock on device (in sync %d)\n", */
+   /*   mdname(mddev), mddev->in_sync); */

    if (mddev->queue)
        blk_add_trace_msg(mddev->queue, "md md_update_sb");
@@ -2563,9 +2563,9 @@ void md_update_sb(struct mddev *mddev, int force_change)
            md_super_write(mddev,rdev,
                       rdev->sb_start, rdev->sb_size,
                       rdev->sb_page);
-           pr_debug("md: (write) %s's sb offset: %llu\n",
-                bdevname(rdev->bdev, b),
-                (unsigned long long)rdev->sb_start);
+           /* pr_debug("md: (write) %s's sb offset: %llu\n", */
+           /*   bdevname(rdev->bdev, b), */
+           /*   (unsigned long long)rdev->sb_start); */
            rdev->sb_events = mddev->events;
            if (rdev->badblocks.size) {
                md_super_write(mddev, rdev,
@@ -2575,10 +2575,10 @@ void md_update_sb(struct mddev *mddev, int force_change)
                rdev->badblocks.size = 0;
            }

-       } else
-           pr_debug("md: %s (skipping faulty)\n",
-                bdevname(rdev->bdev, b));
-
+       } else {
+           /* pr_debug("md: %s (skipping faulty)\n", */
+           /*   bdevname(rdev->bdev, b));*/
+       }
        if (mddev->level == LEVEL_MULTIPATH)
            /* only need to write one superblock... */
            break;
@@ -2596,8 +2596,8 @@ void md_update_sb(struct mddev *mddev, int force_change)
        /* have to write it out again */
        goto repeat;
    wake_up(&mddev->sb_wait);
-   if (test_bit(MD_RECOVERY_RUNNING, &mddev->recovery))
-       sysfs_notify(&mddev->kobj, NULL, "sync_completed");
+   /*if (test_bit(MD_RECOVERY_RUNNING, &mddev->recovery)) */
+   /*  sysfs_notify(&mddev->kobj, NULL, "sync_completed"); */

    rdev_for_each(rdev, mddev) {
        if (test_and_clear_bit(FaultRecorded, &rdev->flags))
```
But kpatch-build only works for second one. We always get jump label errors for the first one. 
`/usr/lib/kpatch/create-diff-object: ERROR: md.o: kpatch_regenerate_special_section: 2091: Found a jump label at read_rdev()+0xc5, using key device_private_key.  Jump labels aren't currently supported.  Use static_key_enabled() instead.`
But looks like `read_rdev` is only used by `md_reload_sb`, while we are patching `md_update_sb`. 
(We also did several more experiments, and we found that kpatch-build only works for the patch that the number of deleted lines is equal to the number of added lines in this function. ) 

kpatch-build: 0.7.0
gcc: 7.3.0
kernel version that the patches apply to: 4.14.91

**Comment by joe-lawrence** [comment] 2020-07-13 15:39
Hi @tli16 : this seems like an odd failure mode for sure.  Do you know if the same problem exists with newer versions of kpatch-build?   (v0.7.0 is about a year old by now)

**Comment by vtl** [comment] 2020-07-16 21:38
It fails the same way with kpatch.git as of commit 01b8d34c4b0901b1a8bb3e23cffe7b08f6912a51 and gcc 7.5.0-3ubuntu1~18.04.

**Comment by tli16** [comment] 2020-07-20 04:20
Hi @joe-lawrence I tried kpatch-build v0.8.0 and also got the same error.

**Comment by jpoimboe** [comment] 2020-07-20 14:36
I'm guessing the problem is that related to the fact that read_rdev() uses the `__LINE__` macro in a few places, like:

```
		pr_warn("%s: %d Could not reload rdev(%d) err: %d. Restoring old values\n",
				__func__, __LINE__, rdev->desc_nr, err);
```

so if the number of lines changes before it, then it results in a change to that function as well.

You may need to experiment with either KPATCH_IGNORE_FUNCTION, or replacing uses of __LINE__ with hard-coded values containing the original line number.

**Comment by joe-lawrence** [comment] 2020-07-20 15:24
> I'm guessing the problem is related to the fact that read_rdev() uses the `__LINE__` macro

Sometimes these can pop out by looking at the disassembly of orig and patched functions.  @vtl @tli16 can you attach your `~/.kpatch/tmp/{orig,patched}` md.0 object files?

**Comment by vtl** [comment] 2020-07-20 16:10
Thanks! __LINE__ makes total sense, I didn't think about it...

**Comment by tli16** [comment] 2020-07-20 17:17
[objfiles.tar.gz](https://github.com/dynup/kpatch/files/4949015/objfiles.tar.gz)
I attached the object files. Thanks for looking into this!

**Comment by joe-lawrence** [comment] 2020-07-20 17:58
> [objfiles.tar.gz](https://github.com/dynup/kpatch/files/4949015/objfiles.tar.gz)
> I attached the object files. Thanks for looking into this!

Hi @tli16 , thanks for sending those along. @jpoimboe was correct that line number shift is introducing changes to `read_rdev()`.  Checkout out a comparison of the disassembly below:

```diff
% diff -u \
    <(objdump -D -j .text.read_rdev orig/drivers/md/md.o) \
    <(objdump -D -j .text.read_rdev patched/drivers/md/md.o)

--- /dev/fd/63  2020-07-20 13:52:42.750317050 -0400
+++ /dev/fd/62  2020-07-20 13:52:42.750317050 -0400
@@ -1,5 +1,5 @@
 
-orig/drivers/md/md.o:     file format elf64-x86-64
+patched/drivers/md/md.o:     file format elf64-x86-64
 
 
 Disassembly of section .text.read_rdev:
@@ -107,7 +107,7 @@
  171:  00 
  172:  48 c7 c7 00 00 00 00    mov    $0x0,%rdi
  179:  45 89 e8                mov    %r13d,%r8d
- 17c:  ba db 23 00 00          mov    $0x23db,%edx
+ 17c:  ba dc 23 00 00          mov    $0x23dc,%edx
  181:  48 c7 c6 00 00 00 00    mov    $0x0,%rsi
  188:  e8 00 00 00 00          callq  18d <read_rdev+0x18d>
  18d:  49 8b 7c 24 38          mov    0x38(%r12),%rdi
```
It looks like the `__LINE__` in question has shifted from 9179 down to 9180.

**Comment by tli16** [comment] 2020-07-20 21:45
Thank you all so much!

**Comment by joe-lawrence** [comment] 2020-07-21 20:53
Closing, mystery solved.

**Closed by joe-lawrence** 2020-07-21 20:53 UTC
