### ISSUE TITLE
ERROR: could not insert module kpatch-xxxx.ko: Invalid module format

### ISSUE THREAD

**Issue by luceneli** [dynup/kpatch#587] opened 2016-03-30 05:16 UTC
I tried to use kpatch on self compiled kernel 4.4 on CentOS 7, but it fails. here are my steps and messages:

**$kpatch-build -t drivers/gpu/drm/i915/i915.ko trace.patch -s /home/ttt/workspace/kernel-4.4**
Using source directory at /home/ttt/workspace/kernel-4.4
Testing patch file
checking file drivers/gpu/drm/i915/i915_gem_execbuffer.c
Reading special section data
Building original kernel
Building patched kernel
Extracting new and modified ELF sections
i915_gem_execbuffer.o: changed function: i915_gem_do_execbuffer.isra.21
Patched objects: i915.ko
Building patch module: kpatch-trace.ko
SUCCESS
**$ sudo kpatch load kpatch-trace.ko**
loading core module: /usr/local/lib/kpatch/4.4.0+/kpatch.ko
loading patch module: kpatch-trace.ko
insmod: ERROR: could not insert module kpatch-trace.ko: Invalid module format
kpatch: failed to load module kpatch-trace.ko

dmesg said:
[  693.988994] kpatch: module verification failed: signature and/or required key missing - tainting kernel
[  693.992200] kpatch_trace: no symbol version for module_layout

The Module.symvers was there, but it disappeared after running kpatch-build.
Have you met this issue?

**Comment by luceneli** [comment] 2016-03-31 14:25
The patch is quite simple, it just added one printk in the function i915_gem_do_execbuffer. 
Yes, I can make sure the kernel running is the source I provided to kpatch-build.
And I tried to recompile your kernel with your source directory, reboot into that kernel, and try kpatch-build again. the result is the same.

**Comment by luceneli** [comment] 2016-04-03 03:37
This is my patch, could anyone help here?

$ cat printk.patch 
diff --git a/drivers/gpu/drm/i915/i915_gem.c b/drivers/gpu/drm/i915/i915_gem.c
index dbdee03..bfb123b 100644
--- a/drivers/gpu/drm/i915/i915_gem.c
+++ b/drivers/gpu/drm/i915/i915_gem.c
@@ -1265,6 +1265,7 @@ int __i915_wait_request(struct drm_i915_gem_request *req,
 
 	might_sleep();
 	WARN(!intel_irqs_enabled(dev_priv), "IRQs disabled");
+	printk("<<<");
 
 	if (i915_gem_request_completed(req))
 		return 0;

$kpatch-build  -s /home/zgong5/rpmbuild/BUILD/kernel-4.4.0+ -t drivers/gpu/drm/i915/i915.ko printk.patch

$ sudo kpatch load kpatch-printk.ko 
loading core module: /usr/local/lib/kpatch/4.4.0+/kpatch.ko
loading patch module: kpatch-printk.ko
insmod: ERROR: could not insert module kpatch-printk.ko: Invalid module format
kpatch: failed to load module kpatch-printk.ko

$dmesg
[  658.165926] kpatch: module verification failed: signature and/or required key missing - tainting kernel
[  658.225343] kpatch_printk: no symbol version for module_layout

When kpatch-build runs, it calls "make mrproper"  to delete Module.symvers. is it why no symbol version for module_layout?

**Comment by flaming-toast** [comment] 2016-04-04 04:20
@luceneli Thanks for your patience. I was actually having trouble reproducing the error until I noticed that you supplied the `-t` (target) argument.

So normally, when you finish a complete kernel build, a Module.symvers table is generated at the end, containing a list of all exported symbols from a kernel build. Unfortunately I've discovered that the `-t` option has the side effect of only compiling the relevant portion of the kernel and thus only a partial Module.symvers gets generated, containing only exported symbols from the i915 module. Thus when the patch module gets compiled, it will get compiled with this Module.symvers, which is obviously not complete. This is a bug on our part. For now, please omit the `-t` argument and compile the entire kernel during the patch module build. Try the below command instead (which fixed the module_layout warning for me):
`$ kpatch-build -s /home/zgong5/rpmbuild/BUILD/kernel-4.4.0+ printk.patch`

**Comment by flaming-toast** [comment] 2016-04-11 17:08
Closing this issue since there haven't been responses and issue #589 has been opened. @luceneli please feel free to open another issue if you run into any more problems.

**Closed by flaming-toast** 2016-04-11 17:08 UTC
